void v245_tests(){
 reset();ExecutionMode=EXECUTION_MANUAL;ScanMode=CURRENT_SYMBOL;symbols[u"FX"].ready=false;
 check(OnInit()==INIT_SUCCEEDED,"MANUAL initializes without indicator history");
 SymbolState &s=*g_symbols[0];
 check(ObjectFind(0,s.ManualName(u"BUY"))>=0&&ObjectFind(0,s.ManualName(u"SELL"))>=0,"MANUAL panel exists before ATR readiness");
 check(object_text[s.ManualName(u"BUY")]==u"BUY [WAIT]"&&object_text[s.ManualName(u"BUY_INFO")].find(u"M1 ATR not ready")!=string::npos,"ATR wait is visible without a false SL error");
 PatternSignal empty{};empty.type=PATTERN_NONE;
 check(!s.ExecuteEntry(true,0,empty,true,96)&&order_calls==0,"no MANUAL order while ATR unavailable");
 symbols[u"FX"].ready=true;OnTimer();s.Maintain(true);
 check(ObjectFind(0,s.ManualName(u"SL"))>=0&&objects[s.ManualName(u"SL")]<symbols[u"FX"].bid,"ATR recovery creates a genuine below-Bid SL");
 check(object_text[s.ManualName(u"BUY")]==u"BUY"&&s.g_manualReadiness.find(u"Ready")!=string::npos,"timer updates readiness after M1 ATR arrives");
 MqlTick tick{};SymbolInfoTick(u"FX",tick);double sl=0,tp=0;string reason;
 check(s.BuildManualStopsDetailed(true,tick,96,sl,tp,reason)&&sl==96&&reason.empty(),"distant BUY SL passes its own gate");
 check(s.BuildManualStopsDetailed(false,tick,104,sl,tp,reason)&&sl==104&&reason.empty(),"distant SELL SL passes its own gate");
 check(!s.BuildManualStopsDetailed(true,tick,101,sl,tp,reason)&&reason==u"SL on wrong side","BUY wrong side classified");
 check(!s.BuildManualStopsDetailed(false,tick,99,sl,tp,reason)&&reason==u"SL on wrong side","SELL wrong side classified");
 symbols[u"FX"].stops=10;
 check(!s.BuildManualStopsDetailed(true,tick,99.95,sl,tp,reason)&&reason==u"SL too close","broker distance remains enforced");symbols[u"FX"].stops=0;
 auto wait=[&](string expected){s.RefreshManualPanel();check(object_text[s.ManualName(u"BUY")]==u"BUY [WAIT]","blocked preview remains WAIT");check(object_text[s.ManualName(u"BUY_INFO")].find(expected)!=string::npos,"specific wait reason");check(s.g_manualReadiness.find(u"Ready")==string::npos,"header cannot claim ready while both sides blocked");};
 symbols[u"FX"].atr=.01;wait(u"spread too wide (ATR)");
 check(!s.ExecuteEntry(true,0,empty,true,96)&&order_calls==0,"spread guard remains authoritative");symbols[u"FX"].atr=2;
 fail_copy_buffer=true;wait(u"M1 ATR not ready");fail_copy_buffer=false;
 symbols[u"FX"].minLot=10;wait(u"lot below broker minimum");symbols[u"FX"].minLot=.01;
 free_margin=0;wait(u"insufficient margin");free_margin=100000;
 profit_ok=false;wait(u"profit calculation unavailable");profit_ok=true;
 GlobalVariableSet(AccountIntent(u"FX"),1);wait(u"unresolved order");GlobalVariableSet(AccountIntent(u"FX"),0);
 permissions=false;wait(u"Trading permission");permissions=true;
 MaxPortfolioRiskPercent=.01;auto globalsBefore=globals;double rejected=s.m_portfolioRejects;
 wait(u"portfolio risk blocked");check(globals==globalsBefore&&s.m_portfolioRejects==rejected,"preview does not persist portfolio rejection or reserve an order");
 check(!s.ExecuteEntry(true,0,empty,true,96)&&order_calls==0,"portfolio cap still blocks actual MANUAL entry");MaxPortfolioRiskPercent=3;
 s.g_lastAttemptBar=iTime(u"FX",PERIOD_M1,0);wait(u"one-entry-per-bar");s.g_lastAttemptBar=0;
 symbols[u"FX"].mode=SYMBOL_TRADE_MODE_DISABLED;wait(u"symbol direction blocked");symbols[u"FX"].mode=SYMBOL_TRADE_MODE_FULL;
 GlobalVariableSet(g_execKey,1);wait(u"entry lock busy");GlobalVariableSet(g_execKey,0);
 mono+=4000;wait(u"quote stale");newbar();
 RiskMode=RISK_COMBINED;s.g_mcReady=false;wait(u"Monte Carlo blocks entry");RiskMode=RISK_FIXED_ADJUST;
 s.g_consecutiveLosses=StopAfterConsecutiveLosses;wait(u"DD protection blocked entry");s.g_consecutiveLosses=0;
 objects[s.ManualName(u"SL")]=104;s.RefreshManualPanel();
 check(object_text[s.ManualName(u"SELL")]==u"SELL"&&object_text[s.ManualName(u"BUY")]==u"BUY [WAIT]","SELL readiness follows above-Ask SL");
 double beforeStatusHash=AIHash(s.g_status);auto globalsStable=globals;s.RefreshManualPanel();
 check(AIHash(s.g_status)==beforeStatusHash&&globals==globalsStable,"refresh preserves trading status and safety persistence");
 objects[s.ManualName(u"SL")]=96;long lp=0;double dp=0;s.ChartEvent(CHARTEVENT_OBJECT_DRAG,lp,dp,s.ManualName(u"SL"));
 check(StateGet(s.g_statePrefix+u"manual.sl")==96&&s.g_manualMessage.find(u"NEXT entry")!=string::npos,"drag saves only next-entry SL");
 check(s.ExecuteEntry(true,0,empty,true,96)&&order_calls==1,"valid MANUAL entry still reaches the shared order path");
 OnDeinit(0);
 check(indicators.empty(),"shutdown releases all indicator handles in mock live lifecycle");
 // The engine deliberately has no chart-period input. Simulate chart-change
 // deinit/init repeatedly; native chart switching remains a separate real-MT5 check.
 reset();ExecutionMode=EXECUTION_MANUAL;ScanMode=CURRENT_SYMBOL;
 for(int change=0;change<5;change++){
  check(OnInit()==INIT_SUCCEEDED,"repeated chart-change reinitialization");auto &state=*g_symbols[0];state.Maintain(true);
  state.ReleaseIndicators();fail_atr_handle=true;
  check(state.GetATR(PERIOD_M1,14,1)==0&&state.g_indicators.empty(),"failed ATR creation is not cached");
  state.RefreshManualPanel();check(object_text[state.ManualName(u"BUY_INFO")].find(u"M1 ATR not ready")!=string::npos,"INVALID_HANDLE cannot enable a button");
  fail_atr_handle=false;state.RefreshManualPanel();int h=state.CachedIndicator(0,PERIOD_M1,14);
  check(h!=INVALID_HANDLE&&indicators[h].tf==PERIOD_M1&&indicators[h].period==14,"recreated ATR stays M1/14 independent of chart period");
  check(object_text[state.ManualName(u"BUY")]==u"BUY","recreated M1 handle restores valid readiness");
  auto count=indicators.size();for(int poll=0;poll<5;poll++)state.RefreshManualPanel();
  check(indicators.size()==count,"panel refresh reuses unchanged ATR handle");
  OnDeinit(REASON_CHARTCHANGE);check(indicators.empty(),"chart change releases every cached handle in mock");
 }
 reset();ExecutionMode=EXECUTION_MANUAL;SymbolState trend;setup(trend,u"FX",true);
 string name=trend.LINE_PREFIX+u"TREND_SUPPORT",other=trend.LINE_PREFIX+u"HORIZONTAL_TEST";
 ObjectCreate(0,other,OBJ_HLINE,0,0,99);
 ShowAutoTrendLines=true;
 check(trend.CreateOrUpdateTrendLine(name,server_time-120,100,server_time-60,100,clrOrange),"visible trend creation succeeds");
 check(ObjectFind(0,name)>=0,"ShowAutoTrendLines true draws previous trend object");
 double visibleScore=trend.CalculateLineScore(ENTRY_BUY);bool visibleNear=trend.NearTrend(true);auto virtualBefore=trend.m_trends[0];
 ShowAutoTrendLines=false;
 check(trend.CreateOrUpdateTrendLine(name,server_time-120,100,server_time-60,100,clrOrange),"hidden trend calculation succeeds");
 check(ObjectFind(0,name)<0&&ObjectFind(0,other)>=0&&ObjectFind(0,trend.ManualName(u"SL"))>=0&&ObjectFind(0,trend.ManualName(u"BUY"))>=0,"hide deletes only the automatic trend object");
 check(trend.CalculateLineScore(ENTRY_BUY)==visibleScore&&trend.NearTrend(true)==visibleNear&&trend.m_trends[0].p1==virtualBefore.p1&&trend.m_trends[0].t2==virtualBefore.t2,"hidden trend preserves virtual geometry and LineScore");
 fixture_pattern(u"FX");ShowAutoTrendLines=true;trend.UpdateAutoTrendLines();
 double scoreBefore=trend.CalculateLineScore(ENTRY_BUY);auto support=trend.m_trends[0],resistance=trend.m_trends[1];
 ShowAutoTrendLines=false;trend.UpdateAutoTrendLines();
 check(scoreBefore==trend.CalculateLineScore(ENTRY_BUY)&&support.p1==trend.m_trends[0].p1&&resistance.p1==trend.m_trends[1].p1,"swing calculation runs identically with display off");
 trend.Shutdown();
}
